export const theme = {
  header: {
    height: {
      desktop: '100px',
      mobile: '50px',
    },
  },
  colors: {
    primary: '#430099',
    processing: '#430099',
    error: '#d0021b',
    warning: '#d7c700',
    success: '#4b9e00',
    headingColor: '#101010',
    subTextColor: '#4a4a4a',
    shadowColorPrimary: 'rgba(0, 0, 0, 0.12)',
    borderColorPrimary: '#b3babe',
    classicWhite: '#fff',
    classicBlack: '#000',
    livenessSpinnerPrimary: '#cccccc',
    livenessSpinnerSecondary: 'rgba(255, 255, 255, 0.2)',
    livenessSpinnerBackground: 'rgba(0, 0, 0, 0.5)',
    headerStepsFontColor: '#fff',
    headerStepsPast: '#000',
    headerStepsFuture: '#a3a3a4',
    loaderOverlayBackground: 'rgba(255, 255, 255, 0.8)',
    jsonModalBackground: '#656e78',
    progressRingPrimary: 'rgba(67, 0, 153, 1)',
    progressRingSecondary: 'rgba(67, 0, 153, 0.3)',
    summaryTabActive: '#430099',
    summaryTabInactive: '#a180cc',
    borderOrSeparator: '#4a4a4a',
    borderOrSeparatorDisabled: '#bfbfbf',
  },
  fontFamily: {
    Montserrat: `'Montserrat', sans-serif`,
  },
  fontSizes: {
    button: 16,
    buttonSmaller: 14,
  },
  fontWeights: {
    bold: 600,
    semiBold: 500,
    normal: 400,
  },
  lineHeights: {
    normal: '20px',
  },
  jsonStyle: {
    propertyStyle: { color: '#430099', fontWeight: 600 },
    stringStyle: { color: '#fff', fontStyle: 'italic' },
    booleanTrueStyle: { color: '#429400', fontWeight: 600 },
    booleanFalseStyle: { color: '#D0021B', fontWeight: 600 },
    colonStyle: { color: '#430099' },
    numberStyle: { color: '#fff', fontWeight: 600 },
    braceStyle: { color: '#fff', fontWeight: 600 },
    bracketStyle: { color: '#fff', fontWeight: 600 },
    commaStyle: { color: '#fff', fontWeight: 600 },
  },
};
