export const DOC_SIDE_RULE = {
  CORNERS: 'CORNERS',
  OCR: 'OCR',
  MRZ: 'MRZ',
  FACE: 'FACE',
  PDF417: 'PDF417',
};

export const DOC_TYPE = {
  IDENTITY_CARD: 'IDENTITY_CARD',
  RESIDENT_CARD: 'RESIDENT_CARD',
  PASSPORT: 'PASSPORT',
  DRIVING_LICENSE: 'DRIVING_LICENSE',
  UNKNOWN: 'UNKNOWN',
};

export const LIVENESS_TYPES = {
  HIGH: 'LIVENESS_HIGH',
  PASSIVE: 'LIVENESS_PASSIVE',
};

export const DOC_SIDES = {
  SIDE1: 'SIDE1',
  SIDE2: 'SIDE2',
  BACK: 'BACK',
  FRONT: 'FRONT',
  INSIDE_PAGE: 'INSIDE_PAGE',
  UNKNOWN: 'UNKNOWN',
};

export const TRACKING_POSITION_INFO = {
  TRACKER_POSITION_INFO_GOOD: 'TRACKER_POSITION_INFO_GOOD',
  TRACKER_POSITION_INFO_MOVE_BACK_INTO_FRAME:
    'TRACKER_POSITION_INFO_MOVE_BACK_INTO_FRAME', // No head detected
  TRACKER_POSITION_INFO_CENTER_TURN_RIGHT:
    'TRACKER_POSITION_INFO_CENTER_TURN_RIGHT', // Turn your head right
  TRACKER_POSITION_INFO_CENTER_TURN_LEFT:
    'TRACKER_POSITION_INFO_CENTER_TURN_LEFT', // Turn your head left
  TRACKER_POSITION_INFO_CENTER_ROTATE_UP:
    'TRACKER_POSITION_INFO_CENTER_ROTATE_UP', // Turn your head up
  TRACKER_POSITION_INFO_CENTER_ROTATE_DOWN:
    'TRACKER_POSITION_INFO_CENTER_ROTATE_DOWN', // Turn your head down
  TRACKER_POSITION_INFO_MOVING_TOO_FAST:
    'TRACKER_POSITION_INFO_MOVING_TOO_FAST', // You are moving too fast
  TRACKER_POSITION_INFO_CENTER_TILT_RIGHT:
    'TRACKER_POSITION_INFO_CENTER_TILT_RIGHT', // Tilt your head right
  TRACKER_POSITION_INFO_CENTER_TILT_LEFT:
    'TRACKER_POSITION_INFO_CENTER_TILT_LEFT', // Tilt your head left
  TRACKER_POSITION_INFO_STAND_STILL: 'TRACKER_POSITION_INFO_STAND_STILL', // Stand still
  TRACKER_POSITION_INFO_MOVE_DARKER_AREA:
    'TRACKER_POSITION_INFO_MOVE_DARKER_AREA', // The place is too bright
  TRACKER_POSITION_INFO_MOVE_BRIGHTER_AREA:
    'TRACKER_POSITION_INFO_MOVE_BRIGHTER_AREA', // The place is too dark
  TRACKER_POSITION_INFO_CENTER_MOVE_BACKWARDS:
    'TRACKER_POSITION_INFO_CENTER_MOVE_BACKWARDS', // Move away from the camera
  TRACKER_POSITION_INFO_CENTER_MOVE_FORWARDS:
    'TRACKER_POSITION_INFO_CENTER_MOVE_FORWARDS', // Move closer to the camera
};

export const ARBITRARY_LOADING_PROGRESS_ANIMATION_TIMEOUT = 900;

export const ARBITARY_CAMERA_INITIALIZATION_DELAY = 2000;
